version: "3.4"

# Ubuntu , set this for redpanda to start
# https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_ubuntu/ch04s03.htm

# Clickhouse Table Schema
# create table test(id int, message String) ENGINE=MergeTree() PRIMARY KEY id;

services:
  mysql-master:
    extends:
      file: mysql-master-service.yml
      service: mysql-master

  mysql-slave:
    extends:
      file: mysql-slave-service.yml
      service: mysql-master
    depends_on:
      - mysql-master

  clickhouse:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    extends:
      file: zookeeper-service.yml
      service: zookeeper

  debezium-embedded:
    extends:
      file: debezium-embedded-service.yml
      service: debezium-embedded

  ### MONITORING ####
  prometheus:
    extends:
      file: prometheus-service.yml
      service: prometheus

  grafana:
    build:
      context: ./config/grafana
      args:
        GRAFANA_VERSION: latest
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      - DS_PROMETHEUS=prometheus
      - GF_USERS_DEFAULT_THEME=light
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource,grafana-clickhouse-datasource
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource,grafana-clickhouse-datasource
    depends_on:
      - prometheus
    ## END OF MONITORING ###
