version: "3.4"

services:
  sink-connector:
    image: ${SINK_LIGHTWEIGHT_VERSION}
    entrypoint: ["sh", "-c", "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms4g -Xmx4g -jar /app.jar /config.yml com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication"]
    restart: "no"
    ports:
      - "8083:8083"
      - "5005:5005"
      - "7000:7000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config.yml:/config.yml
