apiVersion: v1
kind: Pod
metadata:
  name: debezium-connect
  namespace: debezium
spec:
  containers:
    - name: connect
      image: debezium/connect:1.9.2.Final
      ports:
        - name: debezium
          containerPort: 8083
          protocol: TCP
      env:
        - name: BOOTSTRAP_SERVERS
          value: "redpanda.redpanda:9092"
        - name: GROUP_ID
          value: "10"
        - name: CONFIG_STORAGE_TOPIC
          value:  "inventory.configs"
        - name: OFFSET_STORAGE_TOPIC
          value:  "inventory.offset"
        - name: STATUS_STORAGE_TOPIC
          value: "inventory.status"
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  namespace: debezium
spec:
  ports:
    - name: debezium
      port: 8083
      targetPort: 8083
  selector:
    app.kubernetes.io/name: debezium-connect
  clusterIP: None
  type: ClusterIP
