apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  namespace: debezium
  name: debezium
  labels:
    strimzi.io/cluster: debezium
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    snapshot.mode: "initial"
    snapshot.locking.mode: "minimal"
    snapshot.delay.ms: "10000"
    include.schema.changes: "true"

    database.hostname: "${MYSQL_HOST}"
    database.port: "${MYSQL_PORT}"
    database.user: "${MYSQL_USER}"
    database.password: "${MYSQL_PASSWORD}"
    database.server.id: "${DATABASE_SERVER_ID}"
    database.server.name: "${DATABASE_SERVER_NAME}"
    database.whitelist: "${MYSQL_DBS}"

    database.history.kafka.bootstrap.servers: "${KAFKA_BOOTSTRAP_SERVERS}"
    database.history.kafka.topic: "${KAFKA_TOPIC}"

    topic.creation.$alias.partitions: 3,
    topic.creation.default.replication.factor: 1,
    topic.creation.default.partitions: 3

    key.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    key.converter.apicurio.registry.url: "${REGISTRY_URL}"
    key.converter.apicurio.registry.auto-register: "true"
    key.converter.apicurio.registry.find-latest: "true"

    value.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    value.converter.apicurio.registry.url: "${REGISTRY_URL}"
    value.converter.apicurio.registry.auto-register: "true"
    value.converter.apicurio.registry.find-latest: "true"
