apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  namespace: debezium
  name: debezium
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.1.0
  replicas: 1
  #image: altinity/debezium-mysql-source-connector:latest
  image: sunsingerus/debezium-mysql-source-connector:latest
  bootstrapServers: redpanda.redpanda:9092
#  tls:
#    trustedCertificates:
#      - secretName: my-cluster-cluster-ca-cert
#        certificate: ca.crt

  # https://kafka.apache.org/documentation/#connectconfigs
  config:
    group.id: 1
    config.storage.topic: config-storage-topic-debezium
    offset.storage.topic: offset-storage-topic-debezium
    status.storage.topic: status-storage-topic-debezium
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
