apiVersion: v1
kind: Pod
metadata:
  name: debezium-connect
  namespace: debezium
spec:
  containers:
    - name: connect
      image: debezium/connect:1.9.2.Final
      imagePullPolicy: IfNotPresent
      ports:
        - name: debezium
          containerPort: 8083
          protocol: TCP
      env:
        - name: BOOTSTRAP_SERVERS
          value: "redpanda.redpanda:9092"
        - name: GROUP_ID
          value: "20"
        - name: CONFIG_STORAGE_TOPIC
          value: "inventory.configs.topic"
        - name: OFFSET_STORAGE_TOPIC
          value:  "inventory.offset.topic"
        - name: STATUS_STORAGE_TOPIC
          value: "inventory.status.topic"
        - name: CONNECT_PLUGIN_PATH
          value: "/kafka/connect,/kafka/non-connect"
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  namespace: debezium
spec:
  ports:
    - name: debezium
      port: 8083
      targetPort: 8083
  selector:
    app.kubernetes.io/name: debezium-connect
  clusterIP: None
  type: ClusterIP
