apiVersion: v1
kind: Secret
metadata:
  namespace: mysql
  name: mysql-credentials
type: Opaque
data:
  # root
  rootUser: cm9vdA==
  # %
  rootHost: JQ==
  # root
  rootPassword: cm9vdA==
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  namespace: mysql
  name: mysql
spec:
  secretName: mysql-credentials
  tlsUseSelfSigned: true
  instances: 1
  router:
    instances: 1
