apiVersion: v1
kind: Secret
metadata:
  name: mypwds
  namespace: mysql
type: Opaque
data:
  rootHost: JQ==
  rootPassword: YWx0aW5pdHk=
  rootUser: cm9vdA==
---
apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mypwds
  instances: 1
  router:
    instances: 1
