global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'jmx'
    static_configs:
      - targets:
          - jmx_exporter:9072
  - job_name: 'sink'
    static_configs:
      - targets:
          - sink:8084
  - job_name: redpanda
    static_configs:
      - targets:
          - kafka:9644
  - job_name: debezium
    static_configs:
      - targets:
          - debezium:8080
