name: Publish Docker images

on: 
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull test images
        run: |
          docker pull altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-kafka
          docker pull altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-lt

      - name: Tag images
        run: |
          docker image tag altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-kafka altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-kafka
          docker image tag altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-lt altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-lt

      - name: Push images
        run: |
          docker push altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-kafka
          docker push altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-lt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip