name: Publish Docker images

on: 
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull test images
        run: |
          docker pull altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-kafka
          docker pull altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-lt
      - name: Tag images
        run: |
          docker image tag altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-kafka altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-kafka
          docker image tag altinityinfra/clickhouse-sink-connector:${{ github.event.release.tag_name }}-test-lt altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-lt
      - name: Push images
        run: |
          docker push altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-kafka
          docker push altinity/clickhouse-sink-connector:${{ github.event.release.tag_name }}-lt