name: Kafka Sink Connector - Pull Request Pipeline

on:
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    branches:
      - '**'

jobs:
  build-kafka-lightweight:
    uses: ./.github/workflows/docker-build.yml

  testflows-kafka:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/testflows-sink-connector-kafka.yml
    with:
      sink_version: ${{ github.event.number }}-${{ github.sha }}-kafka

  java-tests-kafka:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/sink-connector-kafka-tests.yml

  java-tests-lightweight:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/sink-connector-lightweight-tests.yml
