name: Kafka - Java tests

on: 
  workflow_call:

jobs:
  java-kafka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: sink-connector
      run: mvn -B package --file pom.xml
    - name: Run Unit tests
      working-directory: sink-connector
      run: mvn test -Dgroups=IntegrationTest --file pom.xml
