name: Lightweight - Java Tests

on:
  workflow_call:

jobs:
  java-lightweight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install maven
        run: sudo apt-get update && sudo apt-get install -y maven
      - name: Build Library with Maven
        working-directory: sink-connector
        run: mvn install -DskipTests=true
      - name: Build Replicator with Maven
        working-directory: sink-connector-lightweight
        run: mvn test
